plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.pathanimator.sample.kt'

    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.pathanimator.sample.kt"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 5
        versionName "v1.0"

        // Updated to AndroidX runner
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Updated to AndroidX Espresso
    androidTestImplementation "androidx.test.espresso:espresso-core:$rootProject.ext.espressoVersion"

    implementation "androidx.appcompat:appcompat:$rootProject.ext.appcompatVersion"
    implementation "androidx.constraintlayout:constraintlayout:2.1.4" // Updated to stable version
    implementation "androidx.core:core-ktx:$rootProject.ext.ktxVersion"

    testImplementation "junit:junit:$rootProject.ext.junitVersion"

    implementation project(path: ':richpath')
    implementation project(path: ':animator')
}